apiVersion: v1
kind: Pod
metadata:
  name: tutorial-<username>-qaic-inference
  namespace: nrp-training-k8s
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: nrp-training
            operator: In
            values: ["true"]
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: qualcomm.com/qaic
            operator: Exists
  tolerations:
  - key: nautilus.io/reservation
    operator: Equal
    value: nrp
    effect: NoSchedule
  volumes:
  - name: scratch
    emptyDir: {}
  containers:
  - name: qaic-inference
    image: ghcr.io/quic/cloud_ai_inference_ubuntu24:1.20.6.0
    resources:
      limits:
        memory: 16Gi
        cpu: 4
        qualcomm.com/qaic: 1
      requests:
        memory: 16Gi
        cpu: 4
        qualcomm.com/qaic: 1
    command: ["/bin/bash", "-c"]
    args:
    - >-
        cd /scratch;
        export HOME=/scratch;
        source /opt/vllm-env/bin/activate;
        cd /opt/qti-aic/integrations/vllm/examples/offline_inference/;
        python qaic.py;
        sleep infinity;
    volumeMounts:
    - name: scratch
      mountPath: /scratch
